version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
      - static_data_ww:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=1
      - S3_STORAGE_BACKEND=0
      - API_KEY=${API_KEY}
      - MAPS_KEY=${MAPS_KEY}
    depends_on:
      - db
  
  proxy:
    image: proxy:latest
    depends_on:
      - app
      - client
    ports:
      - "8000:8000"
      - "4200:4200"
    volumes:
      - static_data_ww:/vol/static
      - frontend_data:/vol/client
    environment:
      - API_BASE="http://localhost:8080000"
  
  client:
    image: weather-app-frontend:latest
    volumes:
      - frontend_data:/app/dist
    environment:
      - API_BASE="http://localhost:8080000"
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  static_data_ww:
  frontend_data:
